Candy Raffle
Rarity-Extended/RarityExtended pull request #126
Opened 2021-12-19 20:45 UTC by murderteeth

## Description
Add UIs for candy raffle, blood sacrifice, and skin drop results

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Change details
Replace the Spooky Festival tile with a link to the Candy Raffle. Add screens for raffle, sacrifice, and skin drop results.

## Resources
Here are the scripts I used to deploy Raffle.sol and simulate results on localhost:
https://github.com/murderteeth/rarity_skins_drop/tree/mt/scripts/localhost

## ⚠ Not quite working yet
Raffle.winningOdds() was reverting when not enough sums/wallets are entered in the lottery. After entering a bunch, it seems to work. I skipped it for now, it's commented here: https://github.com/murderteeth/RarityExtended/blob/feature/skinDrop/pages/festivals/raffle/index.js#L59

After a sacrifice we'd like to remove the sacrificed summoner from the UI. I tried a few things and landed on this:
https://github.com/murderteeth/RarityExtended/blob/feature/skinDrop/pages/festivals/raffle/sacrifice.js#L37
That still doesn't work tho.

2021-12-21 10:15 UTC, Major-Eth requested changes

2021-12-21 10:15 UTC, Major-Eth commented on components/ButtonCounter.js
> +import ButtonCounterBase	 from	 './ButtonCounterBase';
Could you use absolute import here, instead of relative? 🙏

2021-12-21 10:15 UTC, Major-Eth commented on components/ButtonCounter.js
> +		></ButtonCounterBase>;
```suggestion
		/>;
```

2021-12-21 10:15 UTC, Major-Eth commented on components/ModalSelectAdventurer.js
> +import { useEffect } from 'react/cjs/react.development';
```suggestion

```

2021-12-21 10:15 UTC, Major-Eth commented on components/ModalSelectAdventurer.js
>  import	React, {Fragment, useState}		from	'react';
```suggestion
import	React, {Fragment, useState, useEffect}		from	'react';
```

2021-12-21 10:15 UTC, Major-Eth commented on utils/actions/candyRaffle.js
> +const CONFIRMATIONS = 1
```suggestion
const CONFIRMATIONS = 2
```
Prevent the caching from the free RPC to screw up things

2021-12-21 11:28 UTC, Major-Eth requested changes

2021-12-21 11:28 UTC, Major-Eth commented on components/ModalSelectAdventurer.js
> +                    return !exclusions.includes(adventurer.tokenID);
```suggestion
                    return !exclusions.includes(adventurer?.tokenID);
```

2021-12-21 11:34 UTC, Major-Eth requested changes
You should add this
```
if (toAddress(owner) !== toAddress(address)) {
    set_rarities((prev) => {
        delete prev[tokenID];
        return ({...prev})
    });
    return;
}
return
```

In `contexts/useRarity.js` L.223 (instead of just return) to remove the adventurer from previous mapping if no longer owner

2021-12-21 11:34 UTC, Major-Eth commented on pages/festivals/raffle/sacrifice.js
> +      delete rarities[currentAdventurer.tokenID]
```suggestion

```

2021-12-21 11:34 UTC, Major-Eth commented on pages/festivals/raffle/sacrifice.js
> +      set_rarities({...rarities})
```suggestion
			set_rarities((prev) => {
				delete prev[currentAdventurer.tokenID];
				return ({...prev});
			});
```

2021-12-21 11:37 UTC, Major-Eth requested changes

2021-12-21 11:37 UTC, Major-Eth commented on pages/festivals/raffle/index.js
> +          {1}/{Math.round(odds[1] / odds[0])}
```suggestion
          {1}/{odds[0] === 0 ? 1 : Math.round(odds[1] / odds[0])}
```

2021-12-22 09:59 UTC, murderteeth commented on components/ButtonCounter.js
> +import ButtonCounterBase	 from	 './ButtonCounterBase';
75136d6

2021-12-22 09:59 UTC, murderteeth commented on components/ButtonCounter.js
> +		></ButtonCounterBase>;
713a24a

2021-12-22 10:00 UTC, murderteeth commented on utils/actions/candyRaffle.js
> +const CONFIRMATIONS = 1
713a24a

2021-12-22 10:00 UTC, murderteeth commented on components/ModalSelectAdventurer.js
> +                    return !exclusions.includes(adventurer.tokenID);
713a24a

2021-12-22 10:00 UTC, murderteeth commented on pages/festivals/raffle/index.js
> +          {1}/{Math.round(odds[1] / odds[0])}
713a24a

2021-12-22 10:01 UTC, murderteeth commented on pages/festivals/raffle/sacrifice.js
> +      delete rarities[currentAdventurer.tokenID]
77740c2

2021-12-22 10:01 UTC, murderteeth commented on pages/festivals/raffle/sacrifice.js
> +      set_rarities({...rarities})
77740c2

2021-12-22 10:27 UTC, murderteeth commented
@Major-Eth checkout 710c42a pls, changed the way odds are computed and shown

2021-12-24 09:30 UTC, Major-Eth commented on components/ModalSelectAdventurer.js
>  import	React, {Fragment, useState}		from	'react';
@murderteeth I need this one to be fixed to approve :)

2021-12-27 17:01 UTC, Major-Eth approved these changes

2021-12-27 17:02 UTC, merged